config/routes.rb
House::Application.routes.draw do

  resources :assets do
    member do
      
      get 'preview', :format => 'png'

      get 'small',  :format => 'png' 
      get 'medium', :format => 'png' 
      get 'large',  :format => 'jpg' 
      
      get 'download'
      
    end
  end

  root :to => "assets#index"

end

app/models/asset.rb
# encoding: UTF-8

# 2010-09-22
# Looks after files within the system

class Asset
  
  
  include Mongoid::Document
  include Mongoid::Timestamps

  include Upload::Common
  include Upload::Relationships
  

  embeds_one :metadata

  
  field :name
  field :original_filename  # filename
  field :original_filesize, :type => Integer, :default => 0    # filesize in bytes
  
  field :preview_created_at, :type => DateTime
  field :download_count, :type => Integer, :default => 0  
  
  validate :check_file
  
  
  # Callbacks
  after_create :store!
  after_create :process!
  
  after_destroy :delete_files


  # Why not have a name method to display the name (if set), or display the basename?
  # Because in the asset form the name will automatically be filled in with the basename
  # If we replace the file the old filename will presist. 
  # (as the filename will be prepopulated in the name field when we go to edit the asset)

  def to_s
    name.blank? ? basename : name
  end
  
  # This is where the file (from the filesystem) is assigned to the record
  # Where possible we try to assign the name and filesize of the file
  # Additional metadata will be extracted at a later date
  # 
  def file=(file)
  
    @file = file
    
    # Set the size and filename of the uploaded file
    self.original_filesize = get_filesize
    
    # Encode the result as a utf-8 string
    self.original_filename =  get_original_filename
    
  
  end
  
  alias :size :original_filesize
  
  
  # Returns our original file
  # 
  # If the file is a new record and @file hasn't been set, then we have nothing to give them
  # Otherwise we will return the file (which is the original)
  #
  def file
    @file ||= new_record? ? nil : File.new(path, 'r')
  end
  
  # Return boolean as to weither we have a file
  def file?
    !!file and !file.nil?
  end


  # Typically 'process!' will be called outside outside 
  # of the request responce cycle eg: via delayed job
  def process!
    
    
    # If we have an archive extract it
    # Some files mainly iWork docs are automatically zipped by the browser
    
    # Create thumbnails if we can create a preview
    self.thumbnails.create if self.preview.create
    
    # Attempt to extract metadata
    self.create_metadata
    
  end



  def cache_key
    
    { :id => id,
      :size => size,
      :basename => basename }
  end
  
  # Do we have any usable metadata?
  def metadata?
    
    metadata ? !metadata.empty? : false
  end


  # Keeps a log if how many times an asset has been downloaded
  # Currently only keeps a count but this could be expanded
  def update_download_stats
    
    self.download_count ||= 0
    self.download_count += 1

    save(:validate => false)
    
  end

  class << self
    
    
    def ordered
      criteria.order_by(:created_at.desc)
    end
    
  end



  private
  
  def get_original_filename
    
    # If file hasn't been set return nil
    return nil unless file?
    

    f = @file.respond_to?(:original_filename) ? @file.original_filename : File.basename(@file.path)
    f.force_encoding("utf-8")
    
    
  end

  def get_filesize
    
    # We need to have a file to get the size of the file
    return unless file?

    File.size(file.path) 

  end

  def ok_to_process?
    valid?
  end

  # Check to see if we have a file asssigned (which is a requirement)
  # and check that the file isn't zero bytes
  def check_file

    # Don't do anything unless the file has changed
    if file? or file_has_changed?
    
      validate_file_responds_to_path
      validate_file_is_not_empty
      
    else
      validate_presense_of_file
    end

  end
  
  # If *either* filename or size change, we consider the file to have changed
  def file_has_changed?
    original_filename_changed? or original_filesize_changed?
  end
  
  # Add error if there is no file
  def validate_presense_of_file
    errors.add(:file, 'You need to upload a file') if new_record?
  end
  
  # Add errors if the file is empty
  def validate_file_is_not_empty
    errors.add(:file, 'was zero bytes') if file.nil? or File.size(file).zero?
  end

  # We can only process files (objects that respond to path)
  def validate_file_responds_to_path
    errors.add(:file, "didn't respond to path") unless file.respond_to? :path
  end

  # Create our path to where we need to be stored, then move our file there
  def store!
    
    raise "Unable to store the file" unless file

    # Construct the path in the filesystem
    FileUtils.mkdir_p(File.dirname(path))
    FileUtils.mv(@file.path, path)
    FileUtils.chmod(0644, path)
    
    # Re-assign file
    self.file = File.new(path)
    
  end


  # We'll remove the files by removing the parent directory
  # Called from the after destroy callback
  def delete_files

    # Adding true to force the removal
    # So if the directory doesn't exist we ignore
    FileUtils.remove_dir self.basepath, true
  end

end

app/controllers/assets_controller.rb
# encoding: UTF-8

class AssetsController < ApplicationController
  
  before_filter :get_asset, :except => [ :index, :new, :create ]
  
  # The preview and thumbnails need to have a preview first
  before_filter :check_have_preview, :only => [ :preview, :small, :medium, :large ] 
  
  
  # GET /assets
  # GET /assets.xml
  def index
    
    @asset = Asset.new
    @assets = Asset.ordered

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @assets }
    end
  end

  # GET /assets/1
  # GET /assets/1.xml
  def show
    
    
    @asset.create_metadata unless @asset.metadata?

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/new
  # GET /assets/new.xml
  def new
    @asset = Asset.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @asset }
    end
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.xml
  def create
    @asset = Asset.new(params[:asset])

    respond_to do |format|
      if @asset.save
        format.html { redirect_to(@asset, :notice => "#{@asset} was successfully created") }
        format.xml  { render :xml => @asset, :status => :created, :location => @asset }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /assets/1
  # PUT /assets/1.xml
  def update

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to(@asset, :notice => "#{@asset} was successfully updated") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.xml
  def destroy
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to(assets_url, :notice => "#{@asset} was successfully deleted" ) }
      format.xml  { head :ok }
    end
  end
  
  
  # GET /assets/1/preview
  # GET /assets/1/preview.png
  #
  # If the preview exists we send that down the pipe to the user
  # otherwise we ask the preview model for a missing_path
  # this will take into consideration if we haven't yet attempted to create an index
  def preview

    # Check to see if the image has been modified since they last requested the file
    # if it hasn't then we'll give them a 302, otherwise we'll send the file down the file

    if stale?(:etag => @asset.cache_key, :last_modified => @asset.preview.created_at.utc)
    
      respond_to do |format|
        format.png {
       
          # Send the file down the pipe...
          send_file @asset.preview.path, :type => "image/png", :disposition => "inline", :status => 200
        }
      end
    end
  end
  
  
  # Thumbnails
  #
  #
  # GET /assets/1/small
  # GET /assets/1/small.png
  def small
    
    if stale?(:etag => @asset.cache_key, :last_modified => @asset.preview.created_at.utc)
    
      respond_to do |format|
        format.png {
       
          # Send the file down the pipe...
          send_file @asset.thumbnails[:small].path, :type => "image/png", :disposition => "inline", :status => 200
        }
      end
    end
  end  
  
  # GET /assets/1/medium
  # GET /assets/1/medium.png
  def medium

    if stale?(:etag => @asset.cache_key, :last_modified => @asset.preview.created_at.utc)
    
      respond_to do |format|
        format.png {
       
          # Send the file down the pipe...
          send_file @asset.thumbnails[:medium].path, :type => "image/png", :disposition => "inline", :status => 200
        }
      end
    end
    
  end  
  
  # GET /assets/1/large
  # GET /assets/1/large.png
  def large
    
    
    if stale?(:etag => @asset.cache_key, :last_modified => @asset.preview.created_at.utc)
    
      respond_to do |format|
        format.jpg {
       
          # Send the file down the pipe...
          send_file @asset.thumbnails[:large].path, :type => "image/jpg", :disposition => "inline", :status => 200
        }
      end
    end
    
  end  
  
  
  
  def download
    
    
    # Send the file down the pipe...
    send_file @asset.path, :status => 200
    
    @asset.update_download_stats
    
    
  end
  
  
  
  
  
  private
  
  def get_asset
    @asset = Asset.find(params[:id])
  end
  
  
  # If the asset doesn't have a preview, we need to send down a generic image
  # 
  # Either the preview hasn't been created yet, or we were unable to create one
  #
  # There is a http status code for this situation...
  # 
  # 202 Accepted
  # The request has been accepted for processing
  # but the processing has not been completed. 
  # The request might or might not eventually be acted upon
  # as it might be disallowed when processing
  #
  def check_have_preview

    unless @asset.preview.exists?
    
      if action_name.downcase == 'preview'
        essence = @asset.preview 
      else
        essence = @asset.thumbnails[action_name.to_sym]
      end
      
      send_file essence.missing_path, 
                  :type => "image/#{essence.format}", 
                  :disposition => "inline", 
                  :status => 202
    end
    
    
    
  end
  
end

app/helpers/asset_helper.rb
module AssetHelper
  
  # Outputs html to display an image
  def asset_image_tag asset, size = :preview
    
    url = case when size == :small
            small_asset_url(asset)
          when size == :medium
            medium_asset_url(asset)
          when size == :large
            large_asset_url(asset)
          else
            preview_asset_url(asset)
          end
    
    tag :img, { :src => url, :class => size.to_s }
  end
  
  
  
end

app/views/assets/_crud.html.erb
<div class="crud asset">

	<%= link_to 'Create a new asset', new_asset_path, { 
		:class => 'new', 
		:accesskey => 'n' } unless controller.action_name == 'new' %>

	<%- if @asset && !@asset.new_record? -%>

		<%= link_to 'Show', 
		asset_path(@asset), { 
			:class => 'show',
			:title => "View #{@asset}" } unless controller.action_name == 'show'  %>

		<%= link_to 'Delete', asset_path(@asset), { 
			:confirm => 'You sure you want to delete this asset?', 
			:method => :delete ,
			:class => 'delete',
			:title => "Delete #{@asset}",  
			:accesskey => 'd' } %>
			
			
		<%= link_to 'Download', download_asset_path(@asset), { 
			:class => "download", 
			:title => "Download #{@asset}"
			} %>
			
	
	<%- end -%>
	
	<%= link_to 'Assets page', assets_path, {
		:title => "Go back to the assets page",
		:class => "index"  
	} unless controller.action_name == 'index' %>
	         
</div>

app/views/assets/_form.html.erb
<%= form_for(@asset, :html => { :multipart => true } ) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<div class="fields">
		
		<%= f.label :name %>
		<%= f.text_field :name %>
	
		<%= f.label :file %>
		<%= f.file_field :file %>
		
	</div>


  <div class="actions">
	
    <%= f.submit %>
	<!-- reset link to go in here -->

  </div>
<% end %>

app/views/assets/_metadata.html.erb
<table border="0" cellspacing="0" class="metadata">

	<tr>
		<td class="name">Size</td>
		<td class="value"><%= number_to_human_size @asset.size %></td>
	</tr>
	
	
	<% if @asset.metadata? %>
	
		<% @asset.metadata.humanized_attributes.each_pair do |key, value| %>
		<tr>
			<td class="name"><%= key %></td>
			<td class="value"><%= value %></td>
		</tr>
		<% end %>
		
	
	<% end %>

	<tr>
		<td class="name">Uploaded</td>
		<td class="value"><%= time_ago_in_words @asset.created_at %> ago</td>
	</tr>
	
	<% unless @asset.download_count.zero? %>
	
	<tr>
		<td class="name">Downloaded</td>
		<td class="value"><%= pluralize @asset.download_count, 'time' %></td>
	</tr>
	
	<% end %>
	
</table>


<%= debug @asset.metadata.attributes if @asset.metadata? %>

app/views/assets/edit.html.erb
<%= asset_image_tag @asset, :large %>




<% content_for :side do %>

	<%= render 'metadata' %>
	<%= render 'form' %>
	<%= render 'crud' %>

<% end %>

app/views/assets/index.html.erb
<ol class="assets">
	
<% @assets.each do |asset| %>

	<li class="thumb" id="<%= asset.id %>">
		
		<%= link_to asset do %>
			<span class="frame"><%= asset_image_tag asset, :medium %></span>
			<span class="name"><%= asset.to_s %></span>
		<% end %>
	</li>
<% end %>
</ol>


<% content_for :side do %>

<%= render 'form' %>
<%#= render 'crud' %>

<% end %>

app/views/assets/new.html.erb
<% title "Upload a new asset" %>

<% content_for :side do %>

	<h1>New asset</h1>

	<%= render 'form' %>
	<%= render 'crud' %>

<% end %>

app/views/assets/show.html.erb
<% title @asset %>
<%= asset_image_tag @asset, :preview %>




<% content_for :side do %>


<h1><%= @asset %></h1>

<%= render 'metadata' %>
<%= render 'crud' %>


<% end %>